version: '3.8'

services:
  db:
    image: postgres:15.2
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - auth_network
  app:
    container_name: 'authentication_server'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT}:3000"
    networks:
      - auth_network
    depends_on:
      - db

networks:
  auth_network:
    driver: bridge
    name: auth_network